<?php

namespace AppBundle\Repository;

/**
 * FeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedsRepository extends \Doctrine\ORM\EntityRepository
{
}
